### ISSUE TITLE
I just get a black screen

### ISSUE THREAD

**Issue by Mauladen** [Deathemonic/Cat-Dots#4]
To begin with, I install pure Arch Linux with SDDM, then I install all the dependencies and run your installation script, at the end I reboot and log in but I only see a black screen

**Comment by dannyeg-glitch** [comment]
same here

**Comment by madhavkhoslaa** [comment]
same lol

**Comment by R0ttCyph3r** [comment]
same

**Comment by Deathemonic** [comment]
https://github.com/Deathemonic/Cat-Dots/commit/c86d2d0303151918b4e280fd83488be5ac370f6b
