### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by R0ttCyph3r** [Deathemonic/Cat-Dots#6]
I am using virtual box with bspwm installed with ly display manager. I had some customization and it was working fine but after i rebooted it is not working.

**Comment by Deathemonic** [comment]
I've been getting this issue but I can't seem to replicate it in my end. Try launching a terminal inside bspwm or another window manager and run this command. 

```sh
bash ~/.config/cat-configs/bin/system/autostart.sh
```

And see if polybar runs or the wallpaper change if not it's probably a dependencies problem.

**Comment by R0ttCyph3r** [comment]
![image](https://github.com/Deathemonic/Cat-Dots/assets/146866845/e3deb30f-2676-4d00-85d5-0cc133b76ac4)

this is a fresh install i have done

**Comment by R0ttCyph3r** [comment]
![Screenshot 2024-01-14 203410](https://github.com/Deathemonic/Cat-Dots/assets/146866845/afbb12c8-d432-4fde-b3b8-b4e8d15023fa)

this was one error i got when installing your script

**Comment by R0ttCyph3r** [comment]
i hope this helps in fixing things

**Comment by Deathemonic** [comment]
Can you check if the cat-config folder inside has contents inside

```sh
ls ~/.config/cat-configs/bin/system
```

If so try making the scripts executable

```sh
chmod +x ~/.config/cat-configs/bin/system/*
chmod +x ~/.config/cat-configs/bin/utilities/*
```

And try to run the autostart again

**Comment by Deathemonic** [comment]
I see the problem now it's because the `user-dirs.dirs` file is not in the config folder


Try making a file with a name `user-dirs.dirs` in your `~/.config` folder

This is what you put the the file:
```
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"
XDG_CONFIG_DIR="$HOME/.config"
XDG_CACHE_DIR="$HOME/.cache"
```

**Comment by Deathemonic** [comment]
After that run
```
xdg-user-dirs-update
```


Then try to login back to bspwm

**Comment by R0ttCyph3r** [comment]
Thanks man it is working now

**Comment by Deathemonic** [comment]
https://github.com/Deathemonic/Cat-Dots/commit/c86d2d0303151918b4e280fd83488be5ac370f6b

**Comment by R0ttCyph3r** [comment]
I installed a new vm to check if the script works fine now but the issue still persist because the of these 2 lines not being added:

```
XDG_CONFIG_DIR="$HOME/.config"
XDG_CACHE_DIR="$HOME/.cache"
```

add these to `~/.config/users-dirs.dirs`

**Comment by Deathemonic** [comment]
https://github.com/Deathemonic/Cat-Dots/blob/main/misc%2Fhome%2F.config%2Fuser-dirs.dirs#L9-L10
